### ISSUE TITLE
Permanent diff due to not declaring change triggers

### ISSUE THREAD

**Issue by the-maldridge** [bridgecrewio/terraform-aws-bridgecrew-cloudtrail#4]
https://github.com/bridgecrewio/terraform-aws-bridgecrew-cloudtrail/blob/23d63ba86e9126d7305fbcddde05aae6853cf4ef/bridgecrew_sns_resource.tf#L31

In the referenced line, the trigger is a timestamp, which will always be considered changed.  According to the terraform documentation, triggers should be a dictionary of resources that when changed will trigger this resource to be reprovisioned.  In my environment we run many terraform applies that don't touch bridgecrew resources, so having this as a module that will never converge under any circumstances looks pretty fishy in the output.

**Comment by nimrodkor** [comment]
Thanks @the-maldridge !
You're absolutely right, please check our release `v1.1.1`!
